#!/bin/bash

if [ $# != 1 ]; then
  echo 'Usage: clang-build-x64 <AR name>'
  exit
fi

export CXXFLAGS=${CXXFLAGS}\ "-integrated-as -target x86_64-pc-none-elf64"
export CFLAGS=${CFLAGS}\ "-integrated-as -target x86_64-pc-none-elf64"
export AR=$1

make clean && make

